// <auto-generated />
using System;
using CodeQuest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeQuest.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260711224531_AlinharModeloSecao2")]
    partial class AlinharModeloSecao2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeQuest.Models.CompraLoja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustoGoldPago")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ItemLojaId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemLojaId");

                    b.HasIndex("PlayerId");

                    b.ToTable("ComprasLoja");
                });

            modelBuilder.Entity("CodeQuest.Models.Duvida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MarcadaParaRevisao")
                        .HasColumnType("boolean");

                    b.Property<string>("Pergunta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RespostaJson")
                        .HasColumnType("text");

                    b.Property<int?>("TopicoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TopicoId");

                    b.ToTable("Duvidas");
                });

            modelBuilder.Entity("CodeQuest.Models.Exercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dificuldade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnunciadoJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GabaritoJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TopicoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TopicoId");

                    b.ToTable("Exercicios");
                });

            modelBuilder.Entity("CodeQuest.Models.ItemLoja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("CustoGold")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ItensLoja");
                });

            modelBuilder.Entity("CodeQuest.Models.Missao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ConcluidaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataAlvo")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GoldRecompensa")
                        .HasColumnType("integer");

                    b.Property<string>("OrigemJson")
                        .HasColumnType("text");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TopicoId")
                        .HasColumnType("integer");

                    b.Property<int>("XpRecompensa")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TopicoId");

                    b.ToTable("Missoes");
                });

            modelBuilder.Entity("CodeQuest.Models.MissaoExercicio", b =>
                {
                    b.Property<int>("MissaoId")
                        .HasColumnType("integer");

                    b.Property<int>("ExercicioId")
                        .HasColumnType("integer");

                    b.HasKey("MissaoId", "ExercicioId");

                    b.HasIndex("ExercicioId");

                    b.ToTable("MissaoExercicios");
                });

            modelBuilder.Entity("CodeQuest.Models.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("NotaBoss")
                        .HasColumnType("integer");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Modulos", t =>
                        {
                            t.HasCheckConstraint("CK_Modulo_NotaBoss", "\"NotaBoss\" IS NULL OR \"NotaBoss\" BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("CodeQuest.Models.ModuloPrereq", b =>
                {
                    b.Property<int>("ModuloId")
                        .HasColumnType("integer");

                    b.Property<int>("RequerModuloId")
                        .HasColumnType("integer");

                    b.HasKey("ModuloId", "RequerModuloId");

                    b.HasIndex("RequerModuloId");

                    b.ToTable("ModuloPrereqs");
                });

            modelBuilder.Entity("CodeQuest.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Gold")
                        .HasColumnType("integer");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PocaoStreakAtiva")
                        .HasColumnType("boolean");

                    b.Property<int>("StreakDias")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("UltimoDiaAtivo")
                        .HasColumnType("date");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("XpTotal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Players", t =>
                        {
                            t.HasCheckConstraint("CK_Player_Gold", "\"Gold\" >= 0");
                        });
                });

            modelBuilder.Entity("CodeQuest.Models.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projetos");
                });

            modelBuilder.Entity("CodeQuest.Models.Revisao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AgendadaPara")
                        .HasColumnType("date");

                    b.Property<int>("Ciclo")
                        .HasColumnType("integer");

                    b.Property<bool>("Concluida")
                        .HasColumnType("boolean");

                    b.Property<int>("TentativaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TentativaId")
                        .IsUnique();

                    b.ToTable("Revisoes");
                });

            modelBuilder.Entity("CodeQuest.Models.SessaoFoco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MinutosPlanejados")
                        .HasColumnType("integer");

                    b.Property<int>("MinutosReais")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProjetoId")
                        .HasColumnType("integer");

                    b.Property<int?>("TopicoId")
                        .HasColumnType("integer");

                    b.Property<int>("XpGanho")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ProjetoId");

                    b.HasIndex("TopicoId");

                    b.ToTable("SessoesFoco", t =>
                        {
                            t.HasCheckConstraint("CK_SessaoFoco_Alvo", "num_nonnulls(\"ProjetoId\", \"TopicoId\") = 1");
                        });
                });

            modelBuilder.Entity("CodeQuest.Models.Tentativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExercicioId")
                        .HasColumnType("integer");

                    b.Property<string>("FeedbackJson")
                        .HasColumnType("text");

                    b.Property<int>("Nota")
                        .HasColumnType("integer");

                    b.Property<string>("Resposta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExercicioId");

                    b.ToTable("Tentativas", t =>
                        {
                            t.HasCheckConstraint("CK_Tentativa_Nota", "\"Nota\" BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("CodeQuest.Models.Teste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dificuldade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GapsJson")
                        .HasColumnType("text");

                    b.Property<int?>("Nota")
                        .HasColumnType("integer");

                    b.Property<string>("QuestoesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RespostasJson")
                        .HasColumnType("text");

                    b.Property<int>("TopicoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TopicoId");

                    b.ToTable("Testes", t =>
                        {
                            t.HasCheckConstraint("CK_Teste_Nota", "\"Nota\" IS NULL OR \"Nota\" BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("CodeQuest.Models.Topico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Arquivado")
                        .HasColumnType("boolean");

                    b.Property<int>("ModuloId")
                        .HasColumnType("integer");

                    b.Property<int>("NivelEstimado")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Prioridade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.ToTable("Topicos", t =>
                        {
                            t.HasCheckConstraint("CK_Topico_NivelEstimado", "\"NivelEstimado\" BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("CodeQuest.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CodeQuest.Models.CompraLoja", b =>
                {
                    b.HasOne("CodeQuest.Models.ItemLoja", "ItemLoja")
                        .WithMany("Compras")
                        .HasForeignKey("ItemLojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeQuest.Models.Player", "Player")
                        .WithMany("Compras")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemLoja");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("CodeQuest.Models.Duvida", b =>
                {
                    b.HasOne("CodeQuest.Models.Topico", "Topico")
                        .WithMany("Duvidas")
                        .HasForeignKey("TopicoId");

                    b.Navigation("Topico");
                });

            modelBuilder.Entity("CodeQuest.Models.Exercicio", b =>
                {
                    b.HasOne("CodeQuest.Models.Topico", "Topico")
                        .WithMany("Exercicios")
                        .HasForeignKey("TopicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topico");
                });

            modelBuilder.Entity("CodeQuest.Models.Missao", b =>
                {
                    b.HasOne("CodeQuest.Models.Player", "Player")
                        .WithMany("Missoes")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeQuest.Models.Topico", "Topico")
                        .WithMany()
                        .HasForeignKey("TopicoId");

                    b.Navigation("Player");

                    b.Navigation("Topico");
                });

            modelBuilder.Entity("CodeQuest.Models.MissaoExercicio", b =>
                {
                    b.HasOne("CodeQuest.Models.Exercicio", "Exercicio")
                        .WithMany("Missoes")
                        .HasForeignKey("ExercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeQuest.Models.Missao", "Missao")
                        .WithMany("Exercicios")
                        .HasForeignKey("MissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercicio");

                    b.Navigation("Missao");
                });

            modelBuilder.Entity("CodeQuest.Models.ModuloPrereq", b =>
                {
                    b.HasOne("CodeQuest.Models.Modulo", "Modulo")
                        .WithMany("PreRequisitos")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CodeQuest.Models.Modulo", "RequerModulo")
                        .WithMany()
                        .HasForeignKey("RequerModuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Modulo");

                    b.Navigation("RequerModulo");
                });

            modelBuilder.Entity("CodeQuest.Models.Player", b =>
                {
                    b.HasOne("CodeQuest.Models.Usuario", "Usuario")
                        .WithOne("Player")
                        .HasForeignKey("CodeQuest.Models.Player", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CodeQuest.Models.Revisao", b =>
                {
                    b.HasOne("CodeQuest.Models.Tentativa", "Tentativa")
                        .WithOne("Revisao")
                        .HasForeignKey("CodeQuest.Models.Revisao", "TentativaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tentativa");
                });

            modelBuilder.Entity("CodeQuest.Models.SessaoFoco", b =>
                {
                    b.HasOne("CodeQuest.Models.Player", "Player")
                        .WithMany("SessoesFoco")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeQuest.Models.Projeto", "Projeto")
                        .WithMany("SessoesFoco")
                        .HasForeignKey("ProjetoId");

                    b.HasOne("CodeQuest.Models.Topico", "Topico")
                        .WithMany()
                        .HasForeignKey("TopicoId");

                    b.Navigation("Player");

                    b.Navigation("Projeto");

                    b.Navigation("Topico");
                });

            modelBuilder.Entity("CodeQuest.Models.Tentativa", b =>
                {
                    b.HasOne("CodeQuest.Models.Exercicio", "Exercicio")
                        .WithMany("Tentativas")
                        .HasForeignKey("ExercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercicio");
                });

            modelBuilder.Entity("CodeQuest.Models.Teste", b =>
                {
                    b.HasOne("CodeQuest.Models.Topico", "Topico")
                        .WithMany("Testes")
                        .HasForeignKey("TopicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topico");
                });

            modelBuilder.Entity("CodeQuest.Models.Topico", b =>
                {
                    b.HasOne("CodeQuest.Models.Modulo", "Modulo")
                        .WithMany("Topicos")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("CodeQuest.Models.Exercicio", b =>
                {
                    b.Navigation("Missoes");

                    b.Navigation("Tentativas");
                });

            modelBuilder.Entity("CodeQuest.Models.ItemLoja", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("CodeQuest.Models.Missao", b =>
                {
                    b.Navigation("Exercicios");
                });

            modelBuilder.Entity("CodeQuest.Models.Modulo", b =>
                {
                    b.Navigation("PreRequisitos");

                    b.Navigation("Topicos");
                });

            modelBuilder.Entity("CodeQuest.Models.Player", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("Missoes");

                    b.Navigation("SessoesFoco");
                });

            modelBuilder.Entity("CodeQuest.Models.Projeto", b =>
                {
                    b.Navigation("SessoesFoco");
                });

            modelBuilder.Entity("CodeQuest.Models.Tentativa", b =>
                {
                    b.Navigation("Revisao");
                });

            modelBuilder.Entity("CodeQuest.Models.Topico", b =>
                {
                    b.Navigation("Duvidas");

                    b.Navigation("Exercicios");

                    b.Navigation("Testes");
                });

            modelBuilder.Entity("CodeQuest.Models.Usuario", b =>
                {
                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
